name: Create web app

on:
    workflow_dispatch:

permissions:
  id-token: write 

jobs:
    terraform:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v1
              with:
                terraform_version: 1.11.1
            
            - name: Login to Azure
              uses: azure/login@v2
              with:
                creds: ${{ secrets.ARM_CREDENTIALS }}

            - name: Terraform Init
              working-directory: infra/terraform
              run: terraform init

            - name: Terraform Apply
              working-directory: infra/terraform
              run: terraform apply -auto-approve
