name: Create web app

on:
    workflow_dispatch:

jobs:
    terraform:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v1
              with:
                terraform_version: 1.11.1

            - name: Install Azure CLI
              uses: Azure/cli@v1
              with:
                inlineScript: az --version
            
            - name: Login to Azure
              uses: azure/login@v1
              with:
                client-id: ${{ secrets.ARM_CLIENT_ID }}
                tenant-id: ${{ secrets.ARM_TENANT_ID }}
                subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

            - name: Change to Terraform Directory
              run: cd infra/terraform

            - name: Terraform Init
              run: terraform init

            - name: Terraform Apply
              run: terraform apply -auto-approve