name: Build and deploy Docker container to Azure Web App - testproject-stefansnoek-webapp

on:
  # Trigger the workflow manually
  # push:
  #   branches:
  #     - frontend
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Dit is vereist voor actions/checkout
      id-token: write # Dit is vereist voor het aanvragen van de JWT voor Azure

    steps:
      - name: Checkout frontend branch
        uses: actions/checkout@v4
        with:
          ref: frontend

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t stefansnoek/testproject:latest ./frontend

      - name: Push Docker image to Docker Hub
        run: docker push stefansnoek/testproject:latest

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.ARM_CREDENTIALS }}

      - name: Deploy Docker image to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'testproject-stefansnoek-webapp'  # Azure Web App name
          slot-name: 'Production'                    # Slot name, e.g., 'Production'
          images: 'stefansnoek/testproject:latest'     # Docker image from Docker Hub
          
