name: Build and deploy Docker container to Azure Web App - testproject-stefansnoek-webapp

on:
  # Trigger the workflow manually
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for requesting the JWT
      contents: read   # Required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.ARM_CREDENTIALS }}

      - name: Deploy Docker image to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'testproject-stefansnoek-webapp'  # Azure Web App name
          slot-name: 'Production'                    # Slot name, e.g., 'Production'
          images: 'stefansnoek/testproject:latest'     # Docker image from Docker Hub
          